[program:sanic]
command=/webapps/sanic/venv/bin/uvicorn run:app --host 0.0.0.0 --port 8000 --workers 2 --log-config /webapps/sanic/logging.conf
directory=/webapps/sanic
autostart=true
autorestart=true
stderr_logfile=/mnt/logs/v8/byzz/uvicorn/run.err.log
stdout_logfile=/mnt/logs/v8/byzz/uvicorn/run.out.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=7
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=7
environment=PYTHONPATH='/webapps/sanic/venv/bin/python'
