from sanic import Sanic
import os


_DATABASE_ENV_KEYS = (
    "MYSQL_ENABLED", "MYSQL_HOST", "MYSQL_PORT", "MYSQL_USER", "MYSQL_PASSWORD",
    "MYSQL_DATABASE", "MYSQL_SLAVES",
    "MYSQL_MASTER_HOST", "MYSQL_MASTER_PORT", "MYSQL_MASTER_USER",
    "MYSQL_MASTER_PASSWORD", "MYSQL_MASTER_DATABASE",
    "MYSQL_POOL_SIZE", "MYSQL_POOL_RECYCLE",
    "REDIS_ENABLED", "REDIS_HOST", "REDIS_PORT", "REDIS_PASSWORD", "REDIS_DB",
    "REDIS_EXPIRE", "REDIS_PREFIX", "REDIS_IDLE_TIMEOUT",
    "REDIS_SENTINEL_ENABLED", "REDIS_SENTINELS", "REDIS_MASTER_NAME",
    "MONGO_ENABLED", "MONGODB_HOST", "MONGODB_PORT", "MONGODB_USERNAME",
    "MONGODB_PASSWORD", "MONGODB_DATABASE",
    "SQLITE_ENABLED",
    "ENABLED_DATABASES",
)


def pytest_configure():
    Sanic.test_mode = True
    os.environ["SANIC_ENV"] = "testing"
    for key in _DATABASE_ENV_KEYS:
        os.environ.pop(key, None)
