APP_NAME = "sanic-template"
PROJECT_NAME = "sanic-template"
HOST = "0.0.0.0"
PORT = 8000
WORKERS = 1
DEBUG = False
LANGUAGE = "zh-CN"
ENABLE_AUTH = True
AUTH_WHITE_IP_LIST = []
ENABLE_SIGNING = True
ENABLE_I18N = True
ENABLE_RESPONSE_CACHE = True
CORS_ENABLED = False
CORS_ORIGINS = ["*"]
CORS_ALLOW_METHODS = ["GET", "POST", "PUT", "PATCH", "DELETE", "OPTIONS"]
CORS_ALLOW_HEADERS = ["Content-Type", "Authorization", "X-Request-ID"]
CORS_ALLOW_CREDENTIALS = False
CORS_MAX_AGE = 86400
LOG_TO_FILE = False
LOG_LEVEL = "INFO"
LOG_PATH = "runtime/logs"
LOG_FILE = "app.log"
LOG_FORMATTER = "%(asctime)s [%(levelname)s] [%(name)s] %(message)s"
LOG_MAX_BYTES = 10485760
LOG_BACKUP_COUNT = 7
